### PR TITLE
Token validation

### PR DESCRIPTION
**Pull request by TimMcGilly**
Added token validation api and form. Closes https://github.com/RadiationChallengeProjectCAST/RadDataStorage/issues/8

### CODE REVIEW

**Review by tomkettle1 — APPROVED** [review]
All looks good.

Imma add it as a separate issue but we need to sanitise all these inputs before we let people use this

**Review by dislocated-su — APPROVED** [review]
All looks good. Made a slight change to the UI of the form before merging.

**Comment by TimMcGilly** [comment]
That is a good point and we need to test further however from my brief testing just now I don't believe this validate tokens code is vulnerable to sql injection. Also had a look at readings and think that we are safe from XSS injection because we don't store any user inputted strings. Will have a look at record but think it is safe from sql injection as well.

This is because we are properly using sql parameter (and therefore prepared statement) and not concatenation.

**Comment by tomkettle1** [comment]
Ah, good. I'll leave it as an issue just so we remember to give it a once over before letting people use it, make sure no extra code accidentally makes us vulnerable

**Pull request merged**
