### PR TITLE
Set up ESLint

### PR DESCRIPTION
**Pull request by dislocated-su**
### Description

This PR adds consistent linting using ESLint. The code is linted on save using the ESLint vscode extension.
I've done a cleanup of the code.

There is also a Husky hook that runs the lint before a commit. This has not been tested yet.

### CODE REVIEW

**Review by tomkettle1 — APPROVED** [review]
All looks good to me, but wait until Tim's read through it

**Comment by tomkettle1** [comment]
The only thing I'd say is is it really necessary to reduce the indent amount?

**Comment by dislocated-su** [comment]
Had to rebase to fix all line endings to LF without getting authorship of every single line.

@tomkettle1 The indent amount is indeed small. I'll talk to Tim about this since he suggested ESlint. May modify the rules in ESLint config. Converting this PR to draft until this is resolved.

**Comment by dislocated-su** [comment]
Had to rebase again to change indentation to 4 spaces after discussing with Tim.

We need to make sure that the ESLint extension is installed when developing. I'll add a readme to the project as part of this PR.

**Review by TimMcGilly — APPROVED** [review]

**Pull request merged**
